// BUILD_TIME is baked at build (build-info.js, generated by build-info-gen.js) so it is one constant frozen in the artifact — every serverless invocation reads the SAME instant, which is why timed degradation survives cold starts. No build-info.js (local/CI boot) falls back to process start.
let buildTime;
try {
  buildTime = require("./build-info").BUILD_TIME;
} catch {
  buildTime = Date.now();
}

module.exports = { BUILD_TIME: buildTime };
